name: GitHub Actions Demo
run-name: CI
on: [push, pull_request]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: install node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: install purescript
      run: npm install -g purs

    - name: install spago
      run: npm install -g spago

    - name: run tests
      run: spago test
