name: GitHub Actions Demo
run-name: CI
on: [push, pull_request]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    # - name: install node
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: 18

    - name: install purescript
      uses: purescript-contrib/setup-purescript@main

    - name: run tests
      run: spago test
